apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-operator-catalog
  updateStrategy:
    registryPoll:
      interval: 45m
---
#apiVersion: operators.coreos.com/v1alpha1
#kind: CatalogSource
#metadata:
#  name: ibm-integration-platform-navigator-catalog
#  namespace: openshift-marketplace
#spec:
#  displayName: ibm-integration-platform-navigator-7.1.0
#  publisher: IBM
#  image: icr.io/cpopen/ibm-integration-platform-navigator-catalog@sha256:4d23293d3786fbde27fe064148455ececd456261a2f0c51bb8f6426f8c8c1f25
#  sourceType: grpc
#  updateStrategy:
#    registryPoll:
#      interval: 30m0s
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: opencloud-operators
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp-common-services-1.19.12
  publisher: IBM
  image: icr.io/cpopen/ibm-common-service-catalog@sha256:3466377cc6235f4cb362755422526941a4ad5eec976e1bb88a4126bfa6a9ec46
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: iaf-core-operators
  namespace: openshift-marketplace
spec:
  displayName: IAF Core Operators
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-automation-foundation-core-catalog
  updateStrategy:
    registryPoll:
      interval: 45m
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-automation-processminings
  namespace: openshift-marketplace
spec:
  displayName: IBM ProcessMining Operators
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/processmining-operator-catalog
  updateStrategy:
    registryPoll:
      interval: 45m
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-db2uoperator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM Db2U Catalog
  publisher: IBM
  sourceType: grpc
  image: ibmcom/ibm-db2uoperator-catalog@sha256:7e416ff563492b05daf270e3d8792b1edb70cf6e03bd6a1afca3bc1110f39346
  updateStrategy:
    registryPoll:
      interval: 45m
